### ISSUE TITLE
Chrome Driver Issue

### ISSUE THREAD

**Issue by abrahamjoji** [Microsoft/EasyRepro#105]

**Comment by TYLEROL** [comment]
> System.InvalidOperationException: unknown error: call function result missing 'value'
> (Session info: chrome=65.0.3325.181)
> (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.16299 x86_64)
> 

@abrahamjoji - It looks like you were able to fix this on your own, but as you likely found this is a compatibility issue with the ChromeDriver (v2.31) currently provided with the project. In order to support the v65 release of Google Chrome, EasyRepro will need to be updated with version 2.37 of the ChromeDriver.

Thanks for raising this up. Providing this context in the event others encounter the same issues. The following [article ](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui)describes updating NuGet Packages within the project. Version 2.37 of the ChromeDriver is what will be needed.

If you observe any additional issues while using v2.37 of the ChromeDriver, please open new issues for each and we'll review. This will be helpful in the interim while we work to ensure compatibility with the latest ChromeDriver version.

Regards,
Tyler

**Comment by abrahamjoji** [comment]
@TYLEROL after taking the latest chrome driver its working fine. But the same error is occurred many times. I doubt its something related to identification of control. After login it took some time to load the home page, mostly at that time this error is occurred in my scenarios.
(while seeing the error its shows **Xrm is not found**).
I prefer instead of think time, wait for the the page to load is the better option.

**Comment by TYLEROL** [comment]
@abrahamjoji - for the _Xrm is not defined_ error messages, are they coming from the same method call? Or varying ones?

Internally, we're looking at this error being generated from the CloseGuidedHelp() method included in sample tests. If this is one problem, you can workaround it by disabling GuidedHelp/LearningPath from Org System Settings (_if not required_) and commenting out that line of code.

If you're seeing it from other methods, could you share any other spots you've observed it when using the v2.37 ChromeDriver?

Thanks,
Tyler

**Comment by abrahamjoji** [comment]
Still now its working fine. 
After disabling the CloseGuidedHelp() method it looks good. If anything else comes in between i let you know about it.

**Comment by xbacon29x** [comment]
I already update my webdriver but when I run my script it always prompt this error.

WebDriverException: Message: disconnected: unable to connect to renderer
(Session info: chrome=65.0.3325.181)
(Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.13.0-37-generic x86_64)

**Comment by TYLEROL** [comment]
@xbacon29x - You mentioned that the webdriver update was performed, however in your exception the **Driver info** indicates you're using version 2.31 with the Chrome 65 update.

Can you verify that you've installed the v2.37 ChromeDriver and if the exception is generated again, that it lists version 2.37.XXXXXX in the driver info section? Version 2.36 or 2.37 is required for functionality with the Chrome 65 Update.

[ChromeDriver Downloads](https://sites.google.com/a/chromium.org/chromedriver/downloads)

If these issues persist, could you let us know which Linux distribution / Version you're attempting to execute on?

Regards,
Tyler

**Comment by TYLEROL** [comment]
@abrahamjoji and @xbacon29x - We've released updated branches for v8.2, v9.0 and v9.0.2 last night with bug fixes, enhanced support for the v2.38 ChromeDriver and v3.11.2 Selenium.Support and Selenium.WebDriver. The v9.0.2 branch adds support for the Unified Interface in Dynamics 365.

If you find any problems using the latest versions of code, please raise new issues and we'll promptly review them. Thanks again for using the EasyRepro APIs!

Regards,
Tyler
