### ISSUE TITLE
Custom arguments to ChromeOptions

### ISSUE THREAD

**Issue by NicolasPrats** [Microsoft/EasyRepro#106]
Hi,

For some of our tests, we need to change the default user-agent of Chrome. This could be done by adding an argument to the object `ChromeOptions` but I did not find a way to do this with EasyRepro. Have I missed something ? If not, could you add this possibility please ? 
One simple way to do this could be to mark `virtual ` the methods `ToChrome()`, `ToInternetExplorer()`, … of the class `BrowserOptions`.  So we could extends the default capabilities by creating a new class which inherits the `BrowserOptions `class and overriding the method `ToChrome`().

Regards,

**Comment by TYLEROL** [comment]
Hi @NicolasPrats 

We've added an item to the backlog to consider this change. The easiest change would be your suggestion to mark the methods as virtual so that you could extend them.

If you have anything already implemented, you are welcome to submit a Pull Request of the changes and our team will review them for acceptance into the core branch. If not, we'll consider this for a future release.

Regards,
Tyler
