### ISSUE TITLE
WaitForPageToLoad Not working 

### ISSUE THREAD

**Issue by anilkumarpotluri** [Microsoft/EasyRepro#107]
At the end of  XrmCommandBarPage.ClickCommand  function we are calling driver.WaitForPageToLoad();

It's not waiting for form to load, It's not working after 10th March 2018. It was working perfectly fine before march.

![image](https://user-images.githubusercontent.com/19406814/38038135-fa6bf5ec-32c7-11e8-95ab-d87f73deacaf.png)

Thanks,
Anil.

**Comment by TYLEROL** [comment]
Hi @anilkumarpotluri 

Can you provide some information on the following:

- Which browser / browser version are you utilizing?
- Which web driver and driver version are you using? (e.g ChromeDriver v2.31)

We'll take a look at this and see if we can replicate.

Thanks,
Tyler

**Comment by anilkumarpotluri** [comment]
Hi Tylor,

It's was working with ChromeDriver v2.33 and CRM Version. We started seeing this issue after resent Chrome Updates At the moment we are using ChromeDriver v2.37 and Chrome Browse Version 65.0.3325.181 (Official Build) (64-bit)

Documer.readyState always returning 'Complete' after cling on any command bar button. I could not dig deeper in to it, it may be because 
- Change in behavior in how Chrome handling the script.
- Change in behavior in CRM and how it's loading the Forms.



 

Thanks,
Anil.

**Comment by TYLEROL** [comment]
Hello @anilkumarpotluri,

I know it's been some time since we last looked at this. With the v2.38 ChromeDriver, v3.11.2 Selenium.Support and Selenium.WebDriver, and the v69 Chrome Browser - I do not appear to be able to replicate this issue. 

I also tested with IE and Edge browsers with no repro.

Please re-open this issue if you continue to face this problem and we can take a second look.

Best Regards,
Tyler
