### ISSUE TITLE
Run Test in Multiple Browser at same time

### ISSUE THREAD

**Issue by Nixlene** [Microsoft/EasyRepro#110]
Hi,
Can we run 1 test in multiple browsers at same time.

**Comment by TYLEROL** [comment]
Hello @Nixlene 

Do you have a specific use case you're trying to tackle in this scenario? I would be concerned about the validity of test results in this scenario as each browser will be trying to consume CPU and Memory resources to load/render the Dynamics web pages and would not emulate a real-world user scenario. Each test would likely perform significantly slower vs. testing a single browser at a time.

I'll review with the team on whether this is possible, but would appreciate if you could provide more detail about the scenario you're trying to implement.

Regards,
Tyler

**Comment by Nixlene** [comment]
Thanks Tyler for prompt reply.. as few test cases fails in IE browser.. so wanted to test 1 test case in all 4 browsers(Chrome, IE, Firefox & Edge) preferably in parallel.
As in testsettings.cs I can choose 1 browser at a time, so wondering if multiple browser selection is possible there.

**Comment by TYLEROL** [comment]
@Nixlene - At the moment, the current design for EasyRepro supports 1 browser at a time.

You could create multiple projects/apps with each pointing to a different browser via testsettings.cs and then launch them at the same time if parallel execution is required. It's not a perfect solution, but the only one currently available.

We've added a backlog item for future consideration of this capability, but for now the design will support a single browser.

Regards,
Tyler

**Comment by ikeselman** [comment]
Hi TYLEROL 
How to change  testsettings.cs configurations to run Test Cases in Firefox or IE Browsers
Here mu TestSettings 

using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;

namespace Microsoft.Dynamics365.UIAutomation.Sample
{
    public static class TestSettings
    {
        public static string InvalidAccountLogicalName = "accounts";

        public static LookupItem LookupValues = new LookupItem { Name = "primarycontactid", Value = "Nancy Anderson (sample)" } ;
        public static string LookupField = "primarycontactid";
        public static string LookupName = "Nancy Anderson (sample)";
        private static readonly string Type = System.Configuration.ConfigurationManager.AppSettings["BrowserType"].ToString();
        private static readonly string RemoteType = System.Configuration.ConfigurationManager.AppSettings["RemoteBrowserType"].ToString();
        private static readonly string RemoteHubServerURL = System.Configuration.ConfigurationManager.AppSettings["RemoteHubServer"].ToString();

        public static BrowserOptions Options = new BrowserOptions
        {
            BrowserType = (BrowserType)Enum.Parse(typeof(BrowserType), Type),
            PrivateMode = true,
            FireEvents = false,
            Headless = false,
            UserAgent = false,
            DefaultThinkTime = 2000,
            RemoteBrowserType = (BrowserType)Enum.Parse(typeof(BrowserType), RemoteType),
            RemoteHubServer = new Uri(RemoteHubServerURL),
            UCITestMode = true
        };


I know by default this Demo Project Chrome Browser set 
I just stuck with Chrome issue : 
When I try Run Test "Create Account: WEBTestCreateNewAccount" it is Fail and I am getting into error message:
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 74 though Chrome v74 is installed

Steps I found and done so far, I followed Solution from this link
https://stackoverflow.com/questions/54927496/how-to-download-older-versions-of-chrome-from-a-google-official-site

My issue that when I found version mentioned on NuGet Packages 74.0.3729.6 and attach to "Version Information Tool" I am getting following link
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/638880/
it is installation for Chromium instead of Chrome Browser for Windows 10 64 bit

Any thoughts or may be you come across issues like that 

Thank you very much 

@ikeselman
