### ISSUE TITLE
IE authentication pop-up not handled

### ISSUE THREAD

**Issue by mariana58** [Microsoft/EasyRepro#112]
Login not working in case of authentication pop-up

**Comment by TYLEROL** [comment]
Hello @mariana58 - are you using the automation API's with Dynamics 365 (Online), or with an On-Premises version of the product?

This issue was also faced by another user in #102, and is a limitation of Selenium as the authentication pop-up is not part of a web page. We tried a code sample using Selenium that was suggested in #102, however we could not get that to work successfully.

To interact with the authentication pop-up, if required, I would suggest looking at external options such as AutoAuth for Firefox, or an implementation like AutoIT for Chrome. An example usage of AutoIT can be found [here](http://learn-automation.com/handle-windows-authentication-using-selenium-webdriver/).

I'll review with the team to see if there are any considerations that can be made for this behavior in the future.

Thanks,
Tyler
