### ISSUE TITLE
[BUG] <Facing issue with xrmApp.Grid.OpenRecord(0);>

### ISSUE THREAD

**Issue by Ajay1shetty** [Microsoft/EasyRepro#1242]
## Question

**We are facing issue in this method "xrmApp.Grid.OpenRecord(0);" instead of opening the first record from the grid it is opening some different record which is present on that grid.**

**Comment by aliyoussefi** [comment]
Hi @Ajay1shetty This issue is now fixed in the https://github.com/microsoft/EasyRepro/tree/users/darent%2Fdevelop-2021ReleaseWave2Update branch. [RW2 2021 Branch](https://github.com/microsoft/EasyRepro/tree/users/darent%2Fdevelop-2021ReleaseWave2Update) Can you confirm and open the issue if this is still an active issue?
