### ISSUE TITLE
xrmBrowser.Entity.GetValue returns NoSuchElementException on an entry field

### ISSUE THREAD

**Issue by Tinutza** [Microsoft/EasyRepro#154]
Hi,

I am trying to get the value of a field (which is pre-set to "No") and validate its value . Is not a lookup field, is an entry one (see printscreen attached).

It works the regular way, so I made sure I am in the right frame:

string confidential = xrmBrowser.Driver.FindElement((By.Id("Confidential_label"))).Text;
Console.Out.WriteLine(confidential);
Assert.IsTrue(confidential.Equals("No"));

In case I use the getValue as below i get an error.
string confidential = xrmBrowser.Entity.GetValue("Confidential_label");

The error is:
Message: OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"tag name","selector":"input"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.14393 x86_64)

Am I not using is right?
<img width="517" alt="getvalue" src="https://user-images.githubusercontent.com/40760768/42164490-791bb678-7e06-11e8-8554-c08957707236.PNG">

Kind regards,
Cristina

**Comment by TYLEROL** [comment]
@Tinutza - In the SetValue() or GetValue() methods,  you want to utilize the _schema name_ of the attribute.

In this case, based on the screenshot provided, you should use **db_confidential**


Please let us know if these issues persist after using the schema name of the attribute field.

Thanks!
Tyler

**Comment by Tinutza** [comment]
Hi,

I tried it again and still does not work. 
e.g string confidential = xrmBrowser.Entity.GetValue("db_confidential");

If it works in your environment there any reason why it wouldn't work on this field? I have used GetValue() in the test but only with lookup and dates and it worked: 
e.g string currency = xrmBrowser.Entity.GetValue(new Lookup { Name = "transactioncurrencyid_lookupValue" });

I have version 8.2 but I don't think you have some fixes in this area. Could be that just this field is not working?

Kind regards,
Cristina

**Comment by TYLEROL** [comment]
Thanks @Tinutza for updating. Based on this information you've provided.

To verify one additional scenario - can you confirm whether your transactioncurrency scenario changes if you change the name to match the expected _schema name_ of the field?

From looking at the underlying code, it appears some changes may have occurred to the DOM structure for Dynamics causing the code to not return anticipated text values. The expected design is for the maker to input the schema name of the field, and we'll handle the rest of the DOM in order to return the field value (as opposed to you needing to manually determine whether to target a lookupValue or label element).

 ` string currency = xrmBrowser.Entity.GetValue(new Lookup { Name = "transactioncurrencyid" });`

If the above does not work, then it should confirm the problem for me. Could you also provide the full 8.2 version information for your Dynamics org?

Regards,
Tyler

**Comment by Tinutza** [comment]
Hi,

If I understood correctly I have tried with the following: 
string currency = xrmBrowser.Entity.GetValue("transactioncurrencyid");

It returns null. 
Attached is the printscreen with data-attributename="transactioncurrencyid"

Version of 8.2 is from 15th of february. Probably not the latest, right? 
I can update but just let me know if it makes sense to do so. 

Kind regards,


Cristina
<img width="895" alt="easyrepro_getvalue_bug" src="https://user-images.githubusercontent.com/40760768/42367393-5e4569a6-8104-11e8-8b72-5980ebc73544.PNG">

**Comment by TYLEROL** [comment]
@Tinutza - It doesn't look like the latest code branches have changed anything here - so unnecessary for you to do that at this time (outside of getting other bug fixes).

I'm adding a backlog item to look into this issue and try and get a fix developed for this. Your workarounds should help unblock your scenarios until a fix can be published.

Thanks,
Tyler

**Comment by TYLEROL** [comment]
We've released an array of updates in the latest releases/v9.1 branch that should resolve issues that had been occurring with the GetValue() methods. If you continue to have problems with the latest implementation, please let us know.

e.g.

`string currency = xrmBrowser.Entity.GetValue("transactioncurrencyid").Value;`

Warm Regards,
Tyler
