### ISSUE TITLE
Composite address found places

### ISSUE THREAD

**Issue by Raj137** [Microsoft/EasyRepro#157]
Hi ,

I would like to know how to handle the selection of address found when we enter data in composite address.

![capture](https://user-images.githubusercontent.com/41167231/42653305-57f3a5a4-85d2-11e8-81ef-a8308dc45941.PNG)

**Comment by TYLEROL** [comment]
@Raj137 - Thank you for raising this issue to us. This feature is not currently available within EasyRepro.

I've added an item to our backlog to enhance address input for composite addresses and allow interaction with this dialog. We'll update as soon as this enhancement is made available.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
@Raj137  - Support for this has been added in the latest releases/v9.1 branch. The implementation will "close" the FoundPlaces dialog until the 2nd to last field in the composite control list is reached. This will then by default pick the first address in the list unless otherwise specified. 

If you have issues with the implementation on Entity.SetValue(new CompositeControl{}) please let us know.
