### ISSUE TITLE
Integration with other applications (Katalon, Leapworks)

### ISSUE THREAD

**Issue by markleavesley** [Microsoft/EasyRepro#166]
I've been looking at EasyRepro quite a lot as Dynamics is our core product. We also have increasingly important regular websites that extend our Dynamics offerings. One day these may get rolled into Dynamics Portals, but not today. So I've also been looking at directly coded Selenium, Katalon Studio and tomorrow, Leapworks.

The huge advantage of EasyRepro is the level of abstraction and hopefully version independence, controlling Dynamics using Selenium is a pain. The downside, an equally large downside, it doesn't appear to have a UI, making it somewhat less accessible to the business.

Is it possible to integrate EasyRepro into another application, such as the two I've mentioned, or another? It would be a partnership made in testing heaven. I know that Katalon has packages using Groovy/Java that can introduce new keywords into the test script, whether these can wrap around .NET I don't know, nor do I want to be treading on anybodies toes if somebody else is already looking into this idea.

**Comment by 13rice** [comment]
Hello,

I've discovered Katalon this year, and I'm working daily on Dynamics (but not exclusively on testing). I was surprised that it's i**mpossible to use it with native function and recording**, Dynamics is far too complex (hundred of lines of html/js for a single textfield omg...)

I have successfully make it works copying **EasyRepro C#** function to Groovy and optimizing some functions like SetValue in one function, instead of one function per type. I've seen issues too when I strictly convert a function, I don't know if it's from EasyRepro or Groovy / Katalon.
So **I have converted like half of EasyRepro**, it takes me time, I convert only what I need, step by step. Now **I can do all basic operations from the UI** !! (Navigation, Forms, search), with the custom methods. To complete this task I thought uploading my conversion to github, then everyone can help me in this task, and maybe one day Microsoft will take care of it :)

I'll try to upload everything this week.

**Comment by markleavesley** [comment]
Yes, the Dynamics DOM is crazy. It took me 1/2 day to figure out how to change a text field and save the entity, and deal with the duplicated HTML IDs!

I look forward very much to seeing what you've done and thank you for sharing.

**Comment by markleavesley** [comment]
We have decided not to continue with evaluating EasyRepro. A code only solution is not going to work for us, our testers are not programmers, a home grown wrapper around it is too much of a distraction to our dev resource and we can not rely on the goodwill of an individual or the community to ensure an EasyRepro port is constantly uptodate, and that's even assuming we go with Katalon (we are evaluating Leapwork also which I do not believe is extensible).

EasyRepro needs to come in the box with these and other products to offer codeless Dynamics automation, there must surely be enough demand for this already to justify the business case for formal partnerships/porting.

Thanks for all the support.

**Comment by 13rice** [comment]
Hi,

I've uploaded a starter projet for EasyRepro in Katalon Studio, [here on github](https://github.com/13rice/EasyRepro-Katalon)
There's 3 simple test cases for the moment, Login and Create Account. You have to edit the default profile before launching a test case.
If you are still interested, thanks for any reviews.

**Comment by markleavesley** [comment]
I'm personally very interested to see what you've done but it will be a couple of weeks before I can give it any meaningful time, holidays and work commitments are in the way.
