### ISSUE TITLE
Is the latest version backwards compatible?

### ISSUE THREAD

**Issue by ryan-4** [Microsoft/EasyRepro#177]
The readme syas that Easy Repro supports CRM 365 versions 8.1, 8.2, and 9.0
Does that mean the latest 9.0 Easy Repro release supports all those version, or that I should install the version of Easy Repro that matches the version of our CRM instance?

**Comment by TYLEROL** [comment]
Hello @ryan-4 ,

Yes - our intent is to make each version backwards compatible with previous releases. In some scenarios this is difficult due to occasional changes in the DOM - however we're working to accommodate those scenarios when identified through internal testing or when issues are raised. As an example, if the DOM for a control in v9.0 has changed, we would update the v9.0 branch to handle the new v9 scenario, as well as handling the older method in v8.1 - meaning a v8.1 consumer could use the v9 branch as well.


We are planning to deprecate the v8.1 and v8.2 branches in the very near future and would encourage using the latest available branches. The latest available branch is v9.0.2 which includes the same WebClient code as v9.0, with the addition of the project for UCI features in v9.0.2

Hope this helps!

Best Regards,
Tyler
