### ISSUE TITLE
ContextSwitchDeadlock exception

### ISSUE THREAD

**Issue by skytown32** [Microsoft/EasyRepro#20]
it raised an exceptiono named "ContextSwitchDeadlock" while I'm using the below code:
xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
xrmBrowser.GuidedHelp.CloseGuidedHelp();
xrmBrowser.ThinkTime(500);
xrmBrowser.CommandBar.ClickCommand("CREATE SR");
xrmBrowser.Driver.WaitUntilVisible(OpenQA.Selenium.By.Id("hw_contactphonenumber"));  //raised at the line
xrmBrowser.Entity.SetValue("hw_contactphonenum", "15914314812");

or  set the think time more longer ,like 3000ms , it also raised this exception .

**Comment by TYLEROL** [comment]
Thanks for raising this @skytown32. First off - we want to apologize for the apparent delay in reply to your submission. We've been monitoring issues for quite some time and this one never appeared in the issues list up until two days ago. We spent some time looking into it, but have been unable to determine why this issue was not originally visible to us.

In regards to your exception, the _ContextSwitchDeadlock_ doesn't necessarily mean your code has an issue, just that there is a potential for problem. If you go to Debug > Exceptions in the menu and expand the Managed Debugging Assistants, you will find ContextSwitchDeadlock is enabled. If you disable this, VS will no longer warn you when items are taking a long time to process. In some cases you may validly have a long-running operation. It's also helpful if you are debugging and have stopped on a line while this is processing - you don't want it to complain before you've had a chance to dig into an issue.


1. Is this exception still occurring for you with the latest release? I'd expect so since this is related to Visual Studio configuration, but would like to confirm.

2. Is the exception blocking your tests from completed successfully with a _pass_ marker?

Regards,
Tyler

**Comment by TYLEROL** [comment]
@skytown32 - If you're still facing this issue, please re-open for additional review.

Thanks,
Tyler
