### ISSUE TITLE
Executing test scenarios using multiple user accounts

### ISSUE THREAD

**Issue by veerasekharbathala** [Microsoft/EasyRepro#237]
Hi Team,

How can I use Easy Repro framework to run same test scenarios using different users and roles (ex: sales person, sales manager, sales support, etc.)

Thanks,
Veera

**Comment by MDendura** [comment]
This seems related to #155

**Comment by veerasekharbathala** [comment]
@MDendura - No, I am able run test methods using app.config user name and password. My question is more related to executing same test scenarios using multiple user accounts (as of now we can use only 1 user account details in app.config) either providing multiple user accounts and executing test methods for each user account mentioned in app.config or using one user account, updating user role each time and executing test methods.

Hi Team,
Please find version details below.
EasyRepro version is beta-v9.0.2
D365 version is Version 1710 (9.1.0.288) online
Selenium.Chrome.WebDriver is 2.42.0
Selenium.WebDriver is 3.14.0
Selenium.Support is 3.14.0

**Comment by SantoshDutt** [comment]
Hi @veerasekharbathala you can mention different credentials in the app.config like you said : - either providing multiple user accounts and executing test methods for each user account mentioned in app.config -- 

    <add key="OnlineUsername1" value="user1" />
    <add key="OnlinePassword1" value="****" />
    <add key="OnlineCrmUrl1" value="https;//" />

    <add key="OnlineUsername2" value="user2" />
    <add key="OnlinePassword2" value="****" />
    <add key="OnlineCrmUrl2" value="https://" />

and so on, to check for multiple users with the same test scenarios, 
to implement this method use, 

            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
              User1 test scenarios;
            }

            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
               User2 test scenarios; 
            }
and so on, put the above methods in [TestMethod] and test scenarios seperately.

**Comment by bwmodular** [comment]
@veerasekharbathala 
Another option is to use .runsettings files.

With these you can specify TestRunParameters in this format:

  ```
<TestRunParameters>
    <Parameter name="CRMUserName" value="*****" />
    <Parameter name="CRMPassword" value="*****" />
    <Parameter name="CRMUrl" value="*************************" />
    <Parameter name="browserType" value="chrome" />
  </TestRunParameters>  
```
  
You can then pass the 'test context' in to any methods which need it (such as class initialise) and get the value of the parameter like this:
`testContext.Properties[property].ToString()`

You can then chose which runsettings file you use before running your tests to run the tests with different users, etc.

You can also use these runsettings files in your CI process, so that you could, for example, run your tests with Chrome, then Firefox, then IE after each release to your test environment. 

This article gives much more details:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017
