### ISSUE TITLE
SelectLookup doesn't pick any values

### ISSUE THREAD

**Issue by Dolph-Dragon** [Microsoft/EasyRepro#244]
Hello,

I am having an issue trying to select a value from a LookupField.

My Code : 

Browser xrmBrowser = new Browser(TestSettings.Options);
xrmBrowser.LoginPage.Login(....);
xrmBrowser.ThinkTime(1000);

xrmBrowser.Navigation.OpenSubArea("Vertrieb", "KKB´s");
xrmBrowser.ThinkTime(1000);

xrmBrowser.CommandBar.ClickCommand("Neu");
xrmBrowser.ThinkTime(2000);

xrmBrowser.Entity.SelectLookup("dataport_institutionid", 1);

Expected:  SelectLookup picks the value with the given index (1) and sets the value for the field i chose. (dataport_institutionid) 

Actual: SelectLookup only opens the table with the available values for the chosen field. But it does not pick any value and does not set any value.

Is that a known issue? Is there something wrong with the code? 

Best Regards
Dolph

**Comment by SantoshDutt** [comment]
Hi @Dolph-Dragon ,

 There are two types of Dialogs that open up when we click the lookup button, one includes your - 
"**Dialog_dataport_institutionid_IMenu**" and the other "**Dialog_dataport_institutionid_i_IMenu**"

In the XrmPage, you have methods for select lookup, set value etc etc, 

So, in the  public BrowserCommandResult<bool> SelectLookup(string field, [Range(0, 9)]int index) Method, you have one line which says - 
var dialogName = $"Dialog_{field}_IMenu"; 

currently your lookup field might be in "Dialog_dataport_institutionid_i_IMenu", so duplicate the same method renaming it with SelectLookupWithIMenu and replace the line - 

 var dialogName = $"**Dialog_{field}_i_IMenu**"; instead of var dialogName = $"**Dialog_{field}_IMenu**"; 
Which helps with your scenario.

**Comment by Dolph-Dragon** [comment]
Hello SantoshDutt,

thank you for your fast answer. I added the method.
The new Method works correct for me. 

Best Regards
Dolph
