### ISSUE TITLE
UI test methods for multiple languages

### ISSUE THREAD

**Issue by veerasekharbathala** [Microsoft/EasyRepro#256]
Hi Team,

Our CRM users are using D365 online with English and French languages. Do we need to create separate UI test methods for both English and French versions? 
Or would it be possible to use same UI test methods to test for both English and French versions based on user settings?

Ex: Below command is using display name to open subarea. Would it be possible to use these commands to pass schema / ids as parameters to perform same action? 
   _xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");_

Please find version details below.

EasyRepro version is beta-v9.0.2
D365 version is Version 1710 (9.1.0.853) online
Selenium.Chrome.WebDriver is 2.42.0
Selenium.WebDriver is 3.14.0
Selenium.Support is 3.14.0

Thanks,
Veera

**Comment by TYLEROL** [comment]
Hello @Veerachettebhaktula - Currently, we only support Dynamics 365 Online with the English language. We're doing our best to make each API language independent, however you may encounter issues in some scenarios due to display name changes.

To answer your initial question, you would need to create separate UI methods for both English and French versions based on our current design. In many of the base APIs, Display Name is the desired input which of course will shift from language to language.

It would be possible to setup generic input parameters on each of the APIs, and assign a variable value based on an input language. Based on a desired language value, you could initialize the input parameters (e.g Area and Subarea) to map to the corresponding language value (e.g. Sales/Ventes or Accounts/Comptes).

`xrmBrowser.Navigation.OpenSubArea(Area, Subarea);`

There are some other scenarios that may break outright unfortunately. Multiple language support is an item on the road map to achieve, however we do not have a timeline for when that could be accomplished.

Best Regards,
Tyler
