### ISSUE TITLE
Test Method/ Function for a MultiSelectPicklistControl

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#38]
Hi,

Is there a function/Method to test a MultiSelectPicklistControl field? I haven't found one in the framework (or maybe I've just overlooked it).
This is how I've gotten around to test it but it would be better if it could be done in one line

                xrmBrowser.Entity.SelectSubgridLookup("MultiSelectPicklistControlFieldid", true);
                xrmBrowser.Document.getElementById("MultiSelectPicklistControlFieldid").SendKeys("Value");
                xrmBrowser.Entity.SelectLookup("MultiSelectPicklistControlFieldid_selectAll", 0);

**Comment by dtu11** [comment]
Currently there is not method to set that type of value.  We should add one so I'll add that to our tasks.

**Comment by TYLEROL** [comment]
@troyyer  - Our team has since added capabilities for MultiSelectOptionSet controls in the latest v9.0 branch.

The following is a sample implementation of SetValue for this control type:

`xrmBrowser.Entity.SetValue(new MultiValueOptionSet { Name = "new_multioption", Values = new String[] { "Option1", "Option2" }}, true);
`

The Boolean value can be used if you want to remove any existing values prior to setting the supplied values. By default this is set to false.

If you have any additional questions or with issues implementing this new code, please reactivate this issue.

Thanks!
