### ISSUE TITLE
Select form in UCI(9.1 branch)

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#452]
Hello Team,
For all entities, we are using different forms based on region of the user.
Do we have anything similar to the below select form feasibility for 9.1 version.
`var form = "Details";
                xrmBrowser.Entity.SelectForm(form, 1000);`

**Comment by BillOwens** [comment]
This is a critical need for my company . We have many clients that have multiple forms that we are in the process of starting up testing projects. With UCI becoming the standard, we need this functionality in the UCI side as well as the browser. I am in the middle of setting this up a test and load test for one of our larger clients and we must change forms in order to test.

**Comment by HIREN-AITC** [comment]
We too have a requirement of the same. Can we expect it very soon?
