### ISSUE TITLE
V9.1 XrmApp.GlobalSearch.Search not working as intended

### ISSUE THREAD

**Issue by Bala-Ramadoss** [Microsoft/EasyRepro#504]
The Search String in the above method is not entered in the search input field of the global search area which is against the intended function.

Class: Microsoft.Dynamics365.UIAutomation.Api.UCI.XrmApp

Please rectify the issue asap.

**Comment by Bala-Ramadoss** [comment]
waiting for a resolution on this issue. Please let know

**Comment by Bala-Ramadoss** [comment]
@tyler olson - Any updates on fixes for this issue

**Comment by Bala-Ramadoss** [comment]
@tylerol - Any updates on fix for this issue

**Comment by Bala-Ramadoss** [comment]
@dtu11 @TYLEROL  & team - Request you to Please do the needful by providing a appropriate resolution/fix

**Comment by TYLEROL** [comment]
Hi @Bala-Ramadoss ,

The fix is in PR #546 . This added the following changes:
 
> ChangeSearchType (either CategorizedSearch or RelevanceSearch)
> Filter
> GlobalRelevanceSearchTest
> Updated the following API's
> Updated GlobalSearch to handle both search types
> Updated OpenRecord to handle both search types

Please see the new test sample, UCITestGlobalRelevanceSearch, made available last night via the latest changes in releases/v9.1 branch - or via the 9.1.0.5229 NuGet package.

If you have any issues with these changes, please raise new issues as required.

Warm Regards,
Tyler
