### ISSUE TITLE
Unable to enter DateTime in UCI

### ISSUE THREAD

**Issue by kavitham1985** [Microsoft/EasyRepro#523]
When we try to add date value, it throws error. We used xrmApp.Entity.SetValue("test_evaldate", DateTime.Today.ToShortDateString());

UCI doesnt have DateTimeControl. Interesting thing is, SetValue method was working until last week, now it gives a blank page.
Can you please include DateTimeControl for UCI
I had added this issue under https://github.com/Microsoft/EasyRepro/issues/287. Creating a new issue because that issue is closed

**Comment by kavitham1985** [comment]
@jlattimer @Tylerol FYI

**Comment by jlattimer** [comment]
Submitted  fix for this. I'd also recommend using the overload of SetValue specific to dates. The format should match whatever the logged in user's personal options are set to.
```csharp
xrmApp.Entity.SetValue("new_dateandtimefield", DateTime.Now, "M/d/yyyy h:mm tt");
```
or 
```csharp
xrmApp.Entity.SetValue("new_dateonlyfield", DateTime.Today, "M/d/yyyy");
```

**Comment by kavitham1985** [comment]
Thanks a lot Jason

**Comment by aalad** [comment]
I'm still having a similar issue, can someone help?
All I do is call `xrmApp.Entity.SetValue("estimatedclosedate", DateTime.Today.AddMonths(1), "dd.MM.yyyy"); ` and the result is like this (gif):
![easyrepro_uci_datetime](https://user-images.githubusercontent.com/48445423/75681467-ecbd5380-5c93-11ea-9f0c-0c82c840e5f0.gif)
Then it just stops and the test fails because it's a required field. Sometimes the field says '2020', sometimes it is empty. So it's not consistent what happens.

Thanks in advance!

**Comment by jlattimer** [comment]
You should open a new issue instead of adding on to a closed one.
