### ISSUE TITLE
V9.1 Grid.OpenRecord is not working properly

### ISSUE THREAD

**Issue by Bala-Ramadoss** [Microsoft/EasyRepro#595]
The Grid.OpenRecord method of **Microsoft.Dynamics365.UIAutomation.Api.UCI**  is not opening a record of the grid as it is intended to do.

In few cases instead of opening the record of the grid, it is clicking on a column of the record [which is a link, for example a owner/contact]. Can attach screenshots of the grid if needed.

Code Example:
**_xrmApp** is an instance of the class **Microsoft.Dynamics365.UIAutomation.Api.UCI.XrmApp**

_xrmApp.Grid.OpenRecord(0);

Please resolve this issue asap as it is being used extensively by us.

**Comment by robinsonnemans** [comment]
We had the same problem, the function selects the row it doesn't open it like the function name would suggest. 

Try this:

- Navigate to the OpenGridRow function in Webclient.cs
- Change link.Click() to driver.DoubleClick(link)*;

*might want to create a second function for selecting a row and use the link.Click() for that function so that function won't be lost.

This worked for us, we will commit our fixes for review soon, but in the meantime you could try this out yourself.

**Comment by phuocle** [comment]
I found the root case here. If you have user has a role "Bulk Edit" when you select the grid, the "Ediit" button in the command bar show -> openRecord(0) worked.

If user don't have the "Bulk Edit" role. it fail.

**Comment by rcjohnson113** [comment]
Depends on what grid, is it a grid on the form or an associated grid in the related tab?
