### ISSUE TITLE
How to select the option from suggested drop down list??

### ISSUE THREAD

**Issue by kishkk84** [Microsoft/EasyRepro#599]
## Question

**What is your question?**
How can i select the option from the suggested drop down list. This list will be available and i enter something in address line 1 text field. 

I am looking to select the first option.

I tried the both but none worked:
`xrmBrowser.Entity.SetValue(addressLine1_Textbox_fieldName, "G5 0AP");
LookupItem addressLine1 = new LookupItem { Name = addressLine1_Textbox_fieldName, Index = 0 };
xrmBrowser.Entity.SelectLookup(addressLine1, 0);`

Or
`xrmBrowser.Entity.SetValue(addressLine1_Textbox_fieldName, "G5 0AP");
xrmBrowser.Entity.SelectLookup(addressLine1_Textbox_fieldName, 0);`

See the image for information:
![image](https://user-images.githubusercontent.com/19428883/60524970-740d8e00-9ce5-11e9-866f-82055f8b2dfc.png)

**Comment by rcjohnson113** [comment]
Your addressline1_Textbox_fieldName has to be wrong. Did you create a custom relationship to a custom entity called Country and labeled it Address Line 1. Take that schema name and use it in the lookup.

You can use the Value property in LookupItem as well to set the Lookup instead of index, might be more precise for what you need.


```
            LookupItem addressLine1 = new LookupItem { Name = "new_whateveryoudid", Value = "1 Hunterscraig Drive, GLASGOW, G5" };
            xrmBrowser.Entity.SetValue(addressLine1);
```
```
            xrmBrowser.Entity.SelectLookup("new_whateveryoudid", 0);
```

I always had problems with lookups, there's like 5 different ways to set them.

**Comment by abubakarafzal** [comment]
@rcjohnson113 can you tell me other ways also ?
