### ISSUE TITLE
WaitForTransaction is not working

### ISSUE THREAD

**Issue by Raddyhere** [Microsoft/EasyRepro#683]
Below line in function WaitForTransaction(this IWebDriver driver, int maxWaitTimeInSeconds)
is returning an error "javascript error: Cannot read property 'isAppIdle' of undefined"

Filename - SeleniumExtensions.cs
Line 467 - state = (bool)driver.ExecuteScript("return window.UCWorkBlockTracker.isAppIdle()", "")

**Comment by imartinflores** [comment]
I was going to report the same issue, it stopped working 1 week ago.

**Comment by paarrivanan** [comment]
I am also seeing it. Does anything change with the application. ? I believe there are no framework changes. Same method 'WaitForTransaction' is not working in older versions and newer versions.

I observed this from Yesterday (11/26).

**Comment by mhuguet** [comment]
Apologies to all. A dependent client side API in the UCI platform was removed by our peers. It has been added back and we are working on deploying globally. I'll update this issue once it starts rolling out with the plan.

**Comment by mhuguet** [comment]
Still working on rollout dates. Pushing for sooner than later. Stay tuned.

**Comment by Raddyhere** [comment]
Thankyou Mike!

**Comment by mhuguet** [comment]
It appears that we will be able to have the fix rolled out on Friday, 12/6, to all public cloud regions.

**Comment by TYLEROL** [comment]
In terms of the rollout referenced by Mike this past weekend, the rollout hit the following regions

- Build 9.1.0.11425 deployed to select servers in Australia, North America, Europe, and Canada

- Build 9.1.0.11129 deployed to South America (crm2), Canada (crm3), India (crm8), France (crm12)

- No Deployment to Japan (crm7), Asia Pacific (crm5), UK (crm11), Australia (crm6)

- Build 9.1.0.10740 deployed to Europe (crm4)

- Build 9.1.0.10537 deployed to North America (crm)


The build numbers listed above should have resolved this issue. Please note that due to an issue identified with one of the builds, it was not deployed to Japan, Asia Pacific, United Kingdom, and Australia regions. We expect that should be resolved with a new planned deployment on 12/13.

@Raddyhere / @imartinflores - If you observe information counter to this, and your organization has received an update listed above, please let us know as soon as possible.

Warm Regards,
Tyler

**Comment by TYLEROL** [comment]
Build 9.1.0.11134 was deployed to Japan (crm7), Asia Pacific (crm5), UK (crm11), Australia (crm6) this past weekend. This should provide fix coverage to all public GEOs.

Warm Regards,
Tyler
