### ISSUE TITLE
ClearValue for date field

### ISSUE THREAD

**Issue by ejfdejesus** [Microsoft/EasyRepro#745]
xrmApp.Entity.ClearValue(datefield) is not clearing the date time field.  Is there anyone experiencing this issue? Thanks.

**Comment by AngelRodriguez8008** [comment]
I fix already the date & times. I guest I forgot the ClearValue methods I will check that.

**Comment by ejfdejesus** [comment]
By the way this was working before. Then from 20 January this specific step is always failing.  :)

**Comment by AngelRodriguez8008** [comment]
> By the way this was working before. Then from 20 January this specific step is always failing. :)

Can you please put your whole test hier. I did see any different in ClearValue before & after the 20 January. I will tests your code with both code versions. I think, the problem ist that this method is not done in particular for DateTime Controls, it is generic for text, numbers fields, etc & the time part of the field is a second "input", that seems not be included in this logic.

**Comment by ejfdejesus** [comment]
xrmApp.Entity.SetValue(datetimefield, DateTime.ParseExact("29/09/2019", "dd/MM/yyyy", null), "dd/MM/yyyy");
xrmApp.Entity.ClearValue(datetimefield);

**Comment by AngelRodriguez8008** [comment]
Hi @ejfdejesus,

the PR #749 should solve this Issue. I describe what I think what the problem was. Now you need to clear the field by passing a DateTimeControl to the ClearValue method, exactly like for previously for GetValue.

See the samples [UCITestCreateActivity_ClearDateTimes](https://github.com/microsoft/EasyRepro/blob/005d306bd53e5bd962dc1790e8c155eb04eadf88/Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateActivity.cs#L54) & [UCITestCreateOpportunity_SetHeaderDate](https://github.com/microsoft/EasyRepro/blob/005d306bd53e5bd962dc1790e8c155eb04eadf88/Microsoft.Dynamics365.UIAutomation.Sample/UCI/Create/CreateOpportunity.cs#L43)

**Comment by mVermaat** [comment]
Looks good. I also noticed that in the version before this PR, when you perform a save operation right after setting the datetime field. it isn't saved properly. In example when filling an appointment's end time with '10-10-2020' and 15:00' and pressing save right after the operation. It will save it was '10-10-2020' and '8:00' (default time). 

As you performed some changes in the SetValue method, I'm not sure if the issue still remains but it may be worthwhile to check, My simple workaround is to send a 'Keys.Tab' right after setting the field. It has to do with focus.

**Comment by AngelRodriguez8008** [comment]
Hi @mVermaat,

the workaround by to send a 'Keys.Tab' should not required any more, I made a ClearFocus at the end. That should be enough.

Thanks & br

**Comment by mVermaat** [comment]
I tested against the latest version of the develop branch and it works perfectly. Setting, updating and clearing works great. Thanks @AngelRodriguez8008!

**Comment by AngelRodriguez8008** [comment]
@mVermaat Thank you very much! I appreciate your tests & Feedbacks.
@ejfdejesus Can we close this Issue?

**Comment by ejfdejesus** [comment]
Hi @AngelRodriguez8008 , yes I also tested using the develop branch and it is working fine. Thank you.
