### ISSUE TITLE
How to Select Tab on the UCI form using XrmApp 

### ISSUE THREAD

**Issue by dynamicsk** [Microsoft/EasyRepro#802]
## Question

**What is your question?**
How to Select Tab on the UCI form using XrmApp 

XrmApp.Entity.SelectTab("SUMMARY_TAB");

This is failing 

![image](https://user-images.githubusercontent.com/61816550/76380850-06ebe580-63a8-11ea-8068-63eea5d652dd.png)

**Comment by VasanthChidambaram** [comment]
@dynamicsk - Just provide the tab name. 
`XrmApp.Entity.SelectTab("Summary"); `

**Comment by dynamicsk** [comment]
Hi Vasanth, Thanks for your reply.
 Tried those options. Even i cant select any tab on any entity

**Comment by mVermaat** [comment]
Are you sure you are using the label of the tab not the internal name of the tab?

**Comment by shiyamtj** [comment]
As @mVermaat,
XrmApp.Entity.SelectTab("TabDisplayName") should work without issues. If didn't work, try putting debug point in webclient > SelectTab method to see what element locator your code checking.

**Comment by TYLEROL** [comment]
This was recently broken, but should be fixed in the latest releases/v9.1 branch and 9.1.0.17138 NuGet package released today.

The expected usage is:

`xrmApp.Entity.SelectTab(string tabName, string subNameIfRequired);`

If this is not resolved, please re-open this issue for further discussion.

Warm Regards,
Tyler
