### ISSUE TITLE
[BUG] UCI Entity can't OpenSubGridRecord in subgrid with hidden label

### ISSUE THREAD

**Issue by vaclavrozsypal** [Microsoft/EasyRepro#818]
- [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  - [x] UCI (XrmApp)
  - [x] Online
  - [x] Chrome

can't OpenSubGridRecord in subgrid with hidden label

**Comment by jowells1** [comment]
Currently working on the support on this.  WebClient was parsing based on the label.  Adding the ability to pass the component unique name as well.

**Comment by TYLEROL** [comment]
@vaclavrozsypal - We've introduced support for SubGrids in the latest release. This was merged into the releases/v9.1 branch and the 9.1.0.17138 NuGet Package. Due to the lack of consistency with labels, we shifted the name input to the schema/unique name of the subgrid control on the form. 

The expected usage format is:

xrmApp.Entity.SubGrid.OpenSubGridRecord(string SchemaName, int index);
