### ISSUE TITLE
Visual Studio 2017 crashes when opening the solution

### ISSUE THREAD

**Issue by jeffryvu** [Microsoft/EasyRepro#86]
Opening the solution keeps crashing Visual Studio 2017. I'm running 15.5.7.

Is this a known issue?

**Comment by dtu11** [comment]
I can test the solution with that version of VS and let you know.  Do you have the details of the crash?  Is there anything in the EventLog?

**Comment by dtu11** [comment]
I worked with a team member to install VS 2017 version 15.5.7 on a machine that didn't have everything setup and was able to load the solution and build everything.   We would need to get more information about the crash to determine what the root cause is. 

![image](https://user-images.githubusercontent.com/26821561/36568802-f485b39e-17f0-11e8-8154-d54270c4dd30.png)

**Comment by jeffryvu** [comment]
Ok, thanks for checking! Must be something with my local setup then. I'll troubleshoot it.
