### ISSUE TITLE
[BUG] Unable to  ClickCommand Using RelatedGrid.ClickCommand 

### ISSUE THREAD

**Issue by badarmunir** [Microsoft/EasyRepro#872]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)

**Online or On Premise**
  - [ ] Online

**Browser**
  - [ ] Chrome

**Describe the bug**  
I am trying to click a button In subgrid using ClickCommand method but it's not working

**Code to reproduce**  

I have tried following code  and I am using nugget package 
xrmApp.RelatedGrid.ClickCommand("New Work Order");

xrmApp.RelatedGrid.ClickCommand("New Work Order", "All Visits");

 

**Screenshots**  

![image](https://user-images.githubusercontent.com/23335796/82538889-dd98c400-9b65-11ea-8d05-60dfb6486989.png)
![image](https://user-images.githubusercontent.com/23335796/82539154-63b50a80-9b66-11ea-82b4-0ef58a1b8070.png)

**Comment by dylanhaskins** [comment]
Hey @badarmunir , if you are using the latest NuGet package (published today) then as the grid you are using is a SubGrid and not a RelatedGrid I believe you should be using the new xrmApp.Entity.SubGrid.ClickCommand(SubGridName, Name) i.e xrmApp.Entity.SubGrid.ClickCommand(“All Visits”, "New Work Order")

**Comment by imartinflores** [comment]
@dylanhaskins Hi Dylan, sorry not sure if this is related, but I had the same issue updating the nuget using the CommandBar.ClickCommand("Button1","Button2") was there any changes on this as well ?

I think there is a validation on ClickCommand that is checking the submenu twice, not sure if the second time it validates should be for subSecondmenu.

if (!string.IsNullOrEmpty(subname))

 if (!string.IsNullOrEmpty(subname)) ->  if (!string.IsNullOrEmpty(subSecondmenu))

**Comment by badarmunir** [comment]
@dylanhaskins yes I am using updated nugget package  . and I have changed my code but the issue still exists.
![image](https://user-images.githubusercontent.com/23335796/82563792-1bf7a880-9b91-11ea-832b-81530949bda1.png)

**Comment by TYLEROL** [comment]
Hi @badarmunir - There was a critical change in how to reference subgrids. @dylanhaskins is correct, in this scenario you should use Entity.SubGrid.ClickCommand() as the context of your page is an entity tab containing a subgrid control. Only the 'Related' tab entities use the special RelatedGrid context.

In regards to your posted screenshot, the key problem is you're not referencing the subgrid 'SchemaName/UniqueName'.

In the screenshot below, I've shown how you can determine this using the Inspector in your Browser DevTools. Please let me know if you have any problems after testing using the schemaName of the grid control (Note: this change was made as label was not reliable due to its' ability to be hidden on the form, or in scenarios where two subrids on the form shared a matching label).

![image](https://user-images.githubusercontent.com/29415524/82566809-13c44c80-9b42-11ea-8a90-050533d258b3.png)


Thanks,
Tyler

**Comment by badarmunir** [comment]
@TYLEROL 
There is no schemaName/Unique name 
![image](https://user-images.githubusercontent.com/23335796/82568918-f53d7000-9b98-11ea-8dbb-093d6bc83e37.png)

and I have also tried using 
xrmApp.Entity.SubGrid.ClickCommand(“All Visits”, "New Work Order") it's not working either

**Comment by TYLEROL** [comment]
@badarmunir - If you drill lower in the element structure, you'll come across a div tag that looks like 'DataSetHostContainer_datasetRoot_{subgridSchemaName}'

The ending of that tag will contain the schemaName/UniqueName as referenced in customizations of the environment. The Inspector is the fastest way to find this without having to go drill into system customizations on the form.

**Comment by badarmunir** [comment]
@TYLEROL it worked thanks, now the problem is I have to update all my test cases. But Thanks
